version: "3.9"

networks:
  level4:

services:
  kafka-1:
    image: "confluentinc/cp-kafka:latest"
    networks:
      - "level4"
    ports:
      - "9093:9093"
    environment:
      - "CLUSTER_ID=n6QfYZQpEEOcvNUDutu0TQ"
      - "KAFKA_NODE_ID=1"
      - "KAFKA_PROCESS_ROLES=broker,controller"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      - "KAFKA_LISTENERS=PLAINTEXT://kafka-1:9092"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092"
      - "KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093"
      - "KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT"
